### ISSUE TITLE
M2 - A1 - Utilize an API to collect historical solar panel data from multiple solar installations, including weather conditions, panel specifications, and energy generation measurements

### ISSUE THREAD

**Issue by renovus** [Renovus-Tech/solarec-python#1]

**Comment by fcggamou** [comment]
Related commit: https://github.com/Renovus-Tech/solarec-python/commit/94c54aedb422a04cc6310ad16be42d6aa4ae631b

**Comment by fcggamou** [comment]
Collected data added under:
https://github.com/Renovus-Tech/solarec-python/blob/main/app/ml/data/gen_data.csv
https://github.com/Renovus-Tech/solarec-python/blob/main/app/ml/data/weather_data.csv
