### ISSUE TITLE
M3 - A1 - Gather a dataset of English-language solar installation (with information such as location, installation size, etc.) reports from a few specific providers

### ISSUE THREAD

**Issue by renovus** [Renovus-Tech/solarec-python#5]

**Comment by fcggamou** [comment]
Linked commits are incorrect, the proper related commit is:
https://github.com/Renovus-Tech/solarec-python/commit/e785f1890c25dab2ab8e6b282d2206dac4f755fa

**Comment by fcggamou** [comment]
Synthetically generated reports under:
https://github.com/Renovus-Tech/solarec-python/tree/main/app/ml/data/reports
