### ISSUE TITLE
M3 - A2 - Perform NLP preprocessing and normalization techniques over the dataset

### ISSUE THREAD

**Issue by renovus** [Renovus-Tech/solarec-python#6]

**Comment by fcggamou** [comment]
Related commits:
https://github.com/Renovus-Tech/solarec-python/commit/3a16b321eed1de5432fcfd64f9adeb088233640e
https://github.com/Renovus-Tech/solarec-python/commit/b8c530865643da3439619eb85ef6e346340a5a32

**Comment by fcggamou** [comment]
Related notebook: https://github.com/Renovus-Tech/solarec-python/blob/main/app/ml/notebooks/nlp/1%20-%20Data%20Preprocessing.ipynb
