### ISSUE TITLE
M5 - A1 - Develop list of alerts that are easy to understand to users.

### ISSUE THREAD

**Issue by renovus** [Renovus-Tech/solarec-python#8]
These will help users recognize problems in a timely manner

Test features with users, sampling whether alerts work properly with in-depth fault analysis in 90% of tests

**Comment by fcggamou** [comment]
Related commits:
f47e7d5faf8d14a180952bc5fe9fe4ee6747c922
f47e7d5faf8d14a180952bc5fe9fe4ee6747c922

**Comment by fcggamou** [comment]
Added new endpoint `/solar/alerts`
